name: Android CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: checkout submodule
      run: git submodule sync --recursive && git submodule update --init --recursive

    - name: Skip
      uses: veggiemonk/skip-commit@master
      env:
        COMMIT_FILTER: skip-ci
        
        
    - name: build
      uses: xdtianyu/actions-android-ci@master
      env:
        keypass: ${{ secrets.keypass }}
        storepass: ${{ secrets.storepass }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BUILD_SHA: ${{ github.sha }}
      with: 
        args: '"
        source /opt/setup-android-sdk.sh;
        chmod +x gradlew;
        ./gradlew assembleDebug;
        "'
